### ISSUE TITLE
AFSecurityPolicy.m file error in xcode 6.4

### ISSUE THREAD

**Issue by bhumi19** [AFNetworking/AFNetworking#2907]
AFSecurityPolicy.m  Implicit declaration of function 'SecItemExport' is invalid in C99

error when integrate AFNetworking class

**Comment by koenvanderdrift** [comment]
I can confirm this, it was introduced with commit https://github.com/AFNetworking/AFNetworking/commit/d3391e6618a181a6e1f0b14acf2cb014cc69b121

**Comment by kcharwood** [comment]
I'm trying to get 2.6 out, but ran into one small issue before I had to leave yesterday. If you look at the pod spec currently in the branch, you can see we are setting up that variable if it doesn't exist pre Xcode 7/iOS 9

If you don't install via cocoapods, you'll need to add something similar to the pch.

All of this information is coming soon, but I'm also traveling this week l

**Comment by kcharwood** [comment]
Check the [changelog](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md) here.
