### ISSUE TITLE
Version 2.5.2 NSURLSessionDataTask not found on iOS6.0

### ISSUE THREAD

**Issue by xstone712** [AFNetworking/AFNetworking#2626]
When I update the repository to 2.5.2, I found my app crashed on iOS6.0.
Logs showed: dyld: Symbol not found: _OBJC_CLASS_$_NSURLSessionDataTask....
And it's fine when I used v2.5.0 before.
In my Podfile, I've already used  "platform :ios, '6.0'  to get the version that support iOS6.0.

**Comment by mattt** [comment]
See discussion on #2621.
